buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.13.2'
    }
}

repositories {
    google()
    mavenCentral()
}

apply plugin: 'com.android.application'

android {
    namespace "com.painless.pc"
    compileSdkVersion 36

    defaultConfig {
        applicationId "com.painless.pc"
        minSdkVersion 16
        targetSdkVersion 36
        versionCode 160604
        versionName "6.0.4-gate2a"
    }
    buildTypes {
        debug {
            minifyEnabled false
        }
        release {
            minifyEnabled false
        }
    }
    sourceSets {
        main {
            res.srcDirs = ['res']
            java.srcDirs = ['src']
            manifest.srcFile 'AndroidManifest.xml'
        }
    }
    lintOptions {
        disable 'MissingTranslation'
        disable 'ManifestResource'
        // The legacy config layout intentionally reuses btn_1/btn_2/btn_3 inside
        // section-specific containers. All consumers scope lookup to their container.
        disable 'DuplicateIds'
    }
}

dependencies {
    compileOnly files('libs/hidden-apis.jar')
    compileOnly files('libs/hidden-apis_2.jar')
}
